version: '3'
services:

  rabbitmq-dev:
    image: rabbitmq:3.11.28
    ports:
      - 5002:5672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
        
  mongodb-dev:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - 5003:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass 

  api-dev:
    image: api:latest
    ports:
      - 5001:80
    environment:
      RMQ_URL: amqp://guest:guest@172.20.233.17:5002/
      MONGO_URL: mongodb://user:pass@172.20.233.17:5003/celery_result_backend 
      WORKERS: 2

  request-dev:
    image: request:latest
    environment:
      API_URL: http://172.20.233.17:5001
      RMQ_URL: amqp://guest:guest@172.20.233.17:5002/
      MONGO_URL: mongodb://user:pass@172.20.233.17:5003/celery_result_backend

  model-gpt2-dev:
    image: model:latest
    environment:
      API_URL: http://172.20.233.17:5001
      RMQ_URL: amqp://guest:guest@172.20.233.17:5002/
      MONGO_URL: mongodb://user:pass@172.20.233.17:5003/celery_result_backend 
      REPO_ID: Intel/dynamic_tinybert #gpt2
    volumes:
      - /Users/yiranshi/.cache/huggingface/hub:/home/celery/.cache/huggingface/hub
    # deploy:
    #   resources:
    #     reservations:
          # devices:
          #   - driver: nvidia
          #     count: 8
          #     capabilities: [gpu]

 



